import pyautogui
import time

print("b")
time.sleep(5)
print("a")
for i in range(11):
    pyautogui.press('tab')

print("c")
pyautogui.press('space')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.press('tab')
pyautogui.press('space')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.press('tab')
pyautogui.write("Saphal Pantha")
pyautogui.press('tab')
pyautogui.write("Saphal Pantha in dev")
pyautogui.press('tab')
pyautogui.write("2060/09/02")
pyautogui.press('tab')
pyautogui.press('space')
pyautogui.press('enter')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('space')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.press('tab')
pyautogui.write("1234567890")
pyautogui.press('tab')
pyautogui.write("1234567890")
pyautogui.press('tab')
pyautogui.write("SaphalPantha@gmail.com")
pyautogui.press('tab')
pyautogui.write("7")
pyautogui.press('tab')
pyautogui.write("Siyari")
pyautogui.press('tab')
pyautogui.write("Rupandehi")
pyautogui.press('tab')
pyautogui.write("Canon")
pyautogui.press('tab')
pyautogui.write("3.5")
pyautogui.press('enter')
print("d")