name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      - name: Add EC2 Host Key to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ec2-65-0-102-176.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          scp -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} -r ubuntu@ec2-65-0-102-176.ap-south-1.compute.amazonaws.com:/project_ttc
